export const ADD_WHO_RSS_ITEMS = 'ADD_WHO_RSS_ITEMS';
export const ADD_WHO_RSS_ITEM = 'ADD_WHO_RSS_ITEM';
export const SET_FEED_ERROR = 'SET_FEED_ERROR';
export const START_FEED_LOADING = 'START_FEED_LOADING';
export const STOP_FEED_LOADING = 'STOP_FEED_LOADING';